### ISSUE TITLE
No bootnode for garnet

### ISSUE THREAD

**Issue by ludns** [latticexyz/redstone-node#1]

**Comment by qbzzt** [comment]
@tchardin , I'm assigning this to you because this requires Garnet p2p.

**Comment by tchardin** [comment]
@qbzzt please use: `--p2p.bootnodes=enr:-J64QM3nCEvp4MQhkZrjnst7X9pzUL7ikW3jL5VXsHMbqw0PCDxEctBPAOGluJgg4-2xk4WeDRPV60_zl52_9cHSceiGAZFS5fg8gmlkgnY0gmlwhCLxekOHb3BzdGFja4SthQEAiXNlY3AyNTZrMaEDb4HiEkpCzMLwzTAGG6pqwxX-7cAKLI_FzZz8EuycauODdGNwgiQGg3VkcIIkBg,enr:-J64QJZJo5gi8EaDBk_qWvhTe1ioAFiSEriXN0XlCEKcpiSSASBBITr1v8vEMBZA4PdHjdwFYlnclDgk4YDLBuYV-oKGAY6lSMgZgmlkgnY0gmlwhAP7R1eHb3BzdGFja4SthQEAiXNlY3AyNTZrMaECvgC27BLpm7ZNcclZOYDJhcTFuuTsJzfvafzbHPlllwaDdGNwgiQGg3VkcIIkBg` Thanks

**Comment by qbzzt** [comment]
Now it is closed, by commit https://github.com/latticexyz/redstone-node/commit/fa3f696fe9ec1b29dff9a55d488c531aac629026
