### ISSUE TITLE
Optionally download snapshot from S3 or R2 on first run to make syncing a node be faster

### ISSUE THREAD

**Issue by ludns** [latticexyz/redstone-node#2]

**Comment by qbzzt** [comment]
@tchardin , I'm assigning this to you because this requires the snapshots to be available. Tell me when there are publicly available snapshots and I'll add this.

**Comment by tchardin** [comment]
Is this all good @qbzzt? Thanks

**Comment by qbzzt** [comment]
Yes. My Redstone node is alternating between being fully in sync, and being one block behind.

**Comment by tchardin** [comment]
Why?

**Comment by qbzzt** [comment]
Because synchronization is not instantaneous. There is always a time lapse between the time a new block is created, and the time it's available on a replica.
