### ISSUE TITLE
Granite Mainnet Support

### ISSUE THREAD

**Issue by pc-quiknode** [latticexyz/redstone-node#3]
Hello 
Do you plan to support the [Granite Mainnet activation](https://github.com/ethereum-optimism/op-geth/releases/tag/v1.101408.0)?

**Comment by qbzzt** [comment]
I assume we will, eventually - but I don't know when. Can you [join our discord](https://discord.com/invite/latticexyz) and ask [there](https://discord.com/channels/865335009915961364/1174270077189767259)?
